app:
    name: task-service
    version: 0.1

auth:
    host: 0.0.0.0
    port: 8082
    maxConnectionIdle: 5 # Minutes
    timeout: 15 # Seconds
    maxConnectionAge: 5 # Minutes
    secretKey: 628f955942efffd7e8e30256

rest:
    host: 0.0.0.0
    port: 3001
    debugPort: 9000
    ShutdownTimeout: 5 # Seconds
    readTimeout: 15 # Seconds
    writeTimeout: 15 # Seconds
    idleTimeout: 60 # Seconds

database:
    host: 0.0.0.0
    port: 5432
    user:
    password:
    name: task_service
    sslmode: disable
    use_migrations: true
    migrations: "./migrations"
    driver: pgx

jaeger:
    service: team17-task-services
    host: 0.0.0.0
    port: 6831

msgHandler:
    rate_period_seconds: 60
    requests_per_period: 1