CREATE TABLE IF NOT EXISTS status
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_text TEXT
);

INSERT INTO status (id, status_text) VALUES (0, 'undefined');
INSERT INTO status (id, status_text) VALUES (1, 'accept');
INSERT INTO status (id, status_text) VALUES (2, 'reject');
INSERT INTO status (id, status_text) VALUES (3, 'in_process');

CREATE TABLE IF NOT EXISTS tasks
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               TEXT,
    body                TEXT,
    creator_id          integer NOT NULL,
    status_task         INTEGER REFERENCES status(id) ON DELETE CASCADE NOT NULL,
    created_at          TIMESTAMP DEFAULT now()                       NOT NULL,
    updated_at          TIMESTAMP,
    deleted_at          TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE
);

-- CREATE TABLE IF NOT EXISTS tasks
-- (
--     id                  uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
--     title               TEXT,
--     body                TEXT,
--     creator_id          TEXT NOT NULL,
--     status_task         INTEGER REFERENCES status(id) ON DELETE CASCADE NOT NULL,
--     created_at          TIMESTAMP DEFAULT now()                       NOT NULL,
--     updated_at          TIMESTAMP,
--     deleted_at          TIMESTAMP,
--     is_deleted          BOOLEAN NOT NULL DEFAULT FALSE
-- );

CREATE TABLE IF NOT EXISTS signatories
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             INTEGER REFERENCES tasks(id) ON DELETE CASCADE NOT NULL,
    email               TEXT,
    status_task         INTEGER REFERENCES status(id) ON DELETE CASCADE NOT NULL
);

-- CREATE TABLE IF NOT EXISTS signatories
-- (
--     id                  uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
--     task_id             uuid REFERENCES tasks(id) ON DELETE CASCADE NOT NULL,
--     email               TEXT,
--     status_task         INTEGER REFERENCES status(id) ON DELETE CASCADE NOT NULL
-- );